//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DxfFolderPath {
            get {
                return ((string)(this["DxfFolderPath"]));
            }
            set {
                this["DxfFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExportFolderPath {
            get {
                return ((string)(this["ExportFolderPath"]));
            }
            set {
                this["ExportFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal DiametricalDepthOfCut {
            get {
                return ((decimal)(this["DiametricalDepthOfCut"]));
            }
            set {
                this["DiametricalDepthOfCut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal DiametricalRetract {
            get {
                return ((decimal)(this["DiametricalRetract"]));
            }
            set {
                this["DiametricalRetract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal DiametricalXAllowance {
            get {
                return ((decimal)(this["DiametricalXAllowance"]));
            }
            set {
                this["DiametricalXAllowance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal DiametricalZAllowance {
            get {
                return ((decimal)(this["DiametricalZAllowance"]));
            }
            set {
                this["DiametricalZAllowance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal DiametricalFeedRate {
            get {
                return ((decimal)(this["DiametricalFeedRate"]));
            }
            set {
                this["DiametricalFeedRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal FacingDepthOfCut {
            get {
                return ((decimal)(this["FacingDepthOfCut"]));
            }
            set {
                this["FacingDepthOfCut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal FacingRetract {
            get {
                return ((decimal)(this["FacingRetract"]));
            }
            set {
                this["FacingRetract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal FacingXAllowance {
            get {
                return ((decimal)(this["FacingXAllowance"]));
            }
            set {
                this["FacingXAllowance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal FacingZAllowance {
            get {
                return ((decimal)(this["FacingZAllowance"]));
            }
            set {
                this["FacingZAllowance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal FacingFeedRate {
            get {
                return ((decimal)(this["FacingFeedRate"]));
            }
            set {
                this["FacingFeedRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ChockSize {
            get {
                return ((decimal)(this["ChockSize"]));
            }
            set {
                this["ChockSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#5222")]
        public string WorkplaneOriginParameter {
            get {
                return ((string)(this["WorkplaneOriginParameter"]));
            }
            set {
                this["WorkplaneOriginParameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal CollarinoDepthOfCut {
            get {
                return ((decimal)(this["CollarinoDepthOfCut"]));
            }
            set {
                this["CollarinoDepthOfCut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal CollarinoRetract {
            get {
                return ((decimal)(this["CollarinoRetract"]));
            }
            set {
                this["CollarinoRetract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal CollarinoXAllowance {
            get {
                return ((decimal)(this["CollarinoXAllowance"]));
            }
            set {
                this["CollarinoXAllowance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal CollarinoZAllowance {
            get {
                return ((decimal)(this["CollarinoZAllowance"]));
            }
            set {
                this["CollarinoZAllowance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal CollarinoFeedRate {
            get {
                return ((decimal)(this["CollarinoFeedRate"]));
            }
            set {
                this["CollarinoFeedRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal CavaDepthOfCut {
            get {
                return ((decimal)(this["CavaDepthOfCut"]));
            }
            set {
                this["CavaDepthOfCut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal CavaRetract {
            get {
                return ((decimal)(this["CavaRetract"]));
            }
            set {
                this["CavaRetract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal CavaXAllowance {
            get {
                return ((decimal)(this["CavaXAllowance"]));
            }
            set {
                this["CavaXAllowance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal CavaZAllowance {
            get {
                return ((decimal)(this["CavaZAllowance"]));
            }
            set {
                this["CavaZAllowance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal CavaFeedRate {
            get {
                return ((decimal)(this["CavaFeedRate"]));
            }
            set {
                this["CavaFeedRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal DiametricalSpeedLimit {
            get {
                return ((decimal)(this["DiametricalSpeedLimit"]));
            }
            set {
                this["DiametricalSpeedLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal DiametricalSurfaceSpeed {
            get {
                return ((decimal)(this["DiametricalSurfaceSpeed"]));
            }
            set {
                this["DiametricalSurfaceSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal FacingSpeedLimit {
            get {
                return ((decimal)(this["FacingSpeedLimit"]));
            }
            set {
                this["FacingSpeedLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal FacingSurfaceSpeed {
            get {
                return ((decimal)(this["FacingSurfaceSpeed"]));
            }
            set {
                this["FacingSurfaceSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal CollarinoSpeedLimit {
            get {
                return ((decimal)(this["CollarinoSpeedLimit"]));
            }
            set {
                this["CollarinoSpeedLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal CollarinoSurfaceSpeed {
            get {
                return ((decimal)(this["CollarinoSurfaceSpeed"]));
            }
            set {
                this["CollarinoSurfaceSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal CavaSpeedLimit {
            get {
                return ((decimal)(this["CavaSpeedLimit"]));
            }
            set {
                this["CavaSpeedLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal CavaSurfaceSpeed {
            get {
                return ((decimal)(this["CavaSurfaceSpeed"]));
            }
            set {
                this["CavaSurfaceSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T2W202")]
        public string DiametricalToolNumber {
            get {
                return ((string)(this["DiametricalToolNumber"]));
            }
            set {
                this["DiametricalToolNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T2W202")]
        public string FacingToolNumber {
            get {
                return ((string)(this["FacingToolNumber"]));
            }
            set {
                this["FacingToolNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T2W202")]
        public string CollarinoToolNumber {
            get {
                return ((string)(this["CollarinoToolNumber"]));
            }
            set {
                this["CollarinoToolNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T2W202")]
        public string CavaToolNumber {
            get {
                return ((string)(this["CavaToolNumber"]));
            }
            set {
                this["CavaToolNumber"] = value;
            }
        }
    }
}
